// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SCIMetricAPI.Data;

#nullable disable

namespace SCIMetricAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250331063704_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SCIMetricAPI.Models.CloudProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CloudProviders");
                });

            modelBuilder.Entity("SCIMetricAPI.Models.GridEmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CO2e")
                        .HasColumnType("double");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("GridEmissions");
                });

            modelBuilder.Entity("SCIMetricAPI.Models.InstanceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CPUCoresAvailable")
                        .HasColumnType("int");

                    b.Property<string>("CPUModelName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CloudProviderId")
                        .HasColumnType("int");

                    b.Property<string>("InstanceClass")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MemoryAvailable")
                        .HasColumnType("int");

                    b.Property<int>("TDP")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CloudProviderId");

                    b.ToTable("InstanceTypes");
                });

            modelBuilder.Entity("SCIMetricAPI.Models.InstanceType", b =>
                {
                    b.HasOne("SCIMetricAPI.Models.CloudProvider", "CloudProvider")
                        .WithMany("InstanceTypes")
                        .HasForeignKey("CloudProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CloudProvider");
                });

            modelBuilder.Entity("SCIMetricAPI.Models.CloudProvider", b =>
                {
                    b.Navigation("InstanceTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
